create table phones (id_phone bigint generated by default as identity, city_code varchar(4), country_code varchar(4), number varchar(20), id_user varchar(255), primary key (id_phone));
create table users (id_user varchar(255) not null, created timestamp, email varchar(255), is_active boolean, modified timestamp, last_login timestamp, name varchar(255), password varchar(255), token varchar(2000), primary key (id_user));
alter table phones add constraint FKiekno372qsbmwqaig7ux7dh8f foreign key (id_user) references users;
